### ISSUE TITLE
Clean up README

### ISSUE THREAD

**Issue by nashirj** [tanjyy/ridesio#118]
Now that we've finished demo day, we can clean up the repository to make it a better description of what the app is all about rather than just listing all the features. The GIFs can stay, maybe?

**Comment by tahaafzal5** [comment]
Made changes on the README. Feel free to close this issue when you get a chance to go over the updated README.

**Comment by nashirj** [comment]
Great start! I'll work on this tomorrow some.
- https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project
- https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
- https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3
- https://www.makeareadme.com/

**Comment by nashirj** [comment]
I made a couple changes @tahaafzal5. let me know what you think and if it looks alright feel free to close this issue

**Comment by tahaafzal5** [comment]
Looks great!
