### ISSUE TITLE
AppIcon looks weird on the launch screen

### ISSUE THREAD

**Issue by nashirj** [tanjyy/ridesio#23]
Because the image is a png, the transparent background shows as black rather than white.

Create a higher resolution version of the logo for use throughout the app and place this in the `notes` folder. You don't need to make a pull request, just please let @nashirj know when you do this so that I can 1) replace the `logo` image in the Assets.xcassets folder and 2) update the AppIcon using the Icon Set Creator app.

**Comment by tahaafzal5** [comment]
@nashirj, we can close this as well. If you agree, feel free to.

**Comment by nashirj** [comment]
agreed!
