### ISSUE TITLE
User can access other people's profile screens

### ISSUE THREAD

**Issue by nashirj** [tanjyy/ridesio#49]
- User can see
    - Profile picture
    - First name
    - Last initial
    - Trips currently being offered (slightly different UI so that it's clear this isn't the main feed)

User can get to other people's profile from the feed, the ride details view, their list of trips (which is on their account details page), other people's profiles

**Comment by nashirj** [comment]
- [navigate from UIImage](https://stackoverflow.com/questions/50236308/is-is-possible-to-click-an-imageview-and-open-a-new-view-controller)
- [add gesture to tableviewcell](https://stackoverflow.com/questions/37692978/how-to-add-gesture-to-uitableviewcell)

**Comment by nashirj** [comment]
I need to figure out how to display trips on this screen

**Comment by tahaafzal5** [comment]
Looks great!
