### ISSUE TITLE
Make account details screen

### ISSUE THREAD

**Issue by nashirj** [tanjyy/ridesio#51]
User can see their own
    - First name
    - Last name
    - Phone number
    - Email
    - Profile picture
Upcoming trips (same as on profile screen for others)
    - User can click trip to go to details page.

**Comment by tahaafzal5** [comment]
I believe I did this already. No?

**Comment by nashirj** [comment]
You did, but now you need to make it populate with the user's information by requesting the info from Parse

**Comment by nashirj** [comment]
Closed by #70
