### ISSUE TITLE
Add address/location API to create ride offerings

### ISSUE THREAD

**Issue by yaosarayin** [tanjyy/ridesio#81]

**Comment by nashirj** [comment]
check out #14 for Taha's research on this

**Comment by nashirj** [comment]
I think the Yelpy project also has some information on this

**Comment by nashirj** [comment]
https://stackoverflow.com/questions/33380711/how-to-implement-auto-complete-for-address-using-apple-map-kit

**Comment by nashirj** [comment]
https://www.raywenderlich.com/5247-core-location-tutorial-for-ios-tracking-visited-locations

**Comment by nashirj** [comment]
https://www.raywenderlich.com/7738344-mapkit-tutorial-getting-started

**Comment by nashirj** [comment]
Next thing to do after creating a new modal screen for populating the text field with the result of the above, is to set up a delegate to retrieve the information computed in the modal screen: follow [these instructions](https://fluffy.es/3-ways-to-pass-data-between-view-controllers/)

**Comment by nashirj** [comment]
Code for getting the distance of the ride in miles
``` Swift
import CoreLocation

let coordinate₀ = CLLocation(latitude: 5.0, longitude: 5.0)
let coordinate₁ = CLLocation(latitude: 5.0, longitude: 3.0)

let distanceInMeters = coordinate₀.distance(from: coordinate₁) // result is in meters
let milesPerMeter = 0.000621371192
let distanceInMiles = distanceInMeters * milesPerMeter
```
